### ISSUE TITLE
Investigate slow graph dump

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/gnis-ld.org#19]
@amoeba noticed some slow download speeds for the database dump. Internally, the `dump/` endpoint redirects to GraphDB's repository dump endpoint, which is ultimately responsible for supplying the data. We've been having some issues (Nick says it's the storage on campus) with Kubernetes and one of the issues is slow response time while interacting with kubectl. This may or may not be related to the slow download speed, so retest this once the kubernetes issues are resolved.

**Comment by amoeba** [comment]
Tangentially-related, if we do serve up one or more RDF dumps of the data, I'll put a vote in for using ntriples as the serialization. Turtle is great for viewing small datasets but ntriples is a lot faster to import which I assume is the primary use case. See below for a comparison of import times by format using GraphDB Free:

| dataset         | lines      | turtle | ntriples |
|-----------------|------------|--------|----------|
| feature-aliases | 4,391,246  | 4m7s   | 59s      |
| history         | 791,815    | 17s    | 10s      |
| names           | 11,748,351 | 11m58s | 2m35s    |
| units           | 33,574     | 1s     | <1s      |

Once gzipped, the ntriples files are ~1.4x the size of their turtle equivalent so that is a consideration but I think the improvement in import speed is worth it. Is GraphDB's dump endpoint any faster depending on the serialization format it produces?

**Comment by ThomasThelen** [comment]
Wow! I think those numbers are convincing enough, good to know. It [looks](https://graphdb.ontotext.com/documentation/standard/backing-up-and-recovering-repo.html) like we need to create a custom header and specify the content type [here](https://github.com/DataONEorg/gnis-ld.org/blob/master/lib/js/server.js#L74).

**Comment by ThomasThelen** [comment]
Linking over to https://github.com/DataONEorg/gnis-deployment/issues/13 (I knew I had filed this)
